pyoceans/python-ctd

- CHANGES.txt
- ctd/__init__.py
> Version 0.2.2

- MANIFEST.in
- setup.py
- drop distutils
- add `requirements.txt`
- get `python2 setup.py build` working
> Minor bug fixes

- README.rst
> Updated travis badge

- .travis.yml
- README.rst
- ctd/__init__.py
- ctd/ctd.py
- requirements-dev.txt
...and some minor improvements.
> Some boilerplate stuff

- README.rst
> Add AppVeyor badge

- .travis.yml
- README.rst
- ctd/ctd.py
- ctd/plotting.py
- ctd/processing.py
- tests/test_ctd.py
- tests/test_plotting.py
- tests/test_processing.py
Thanks @rsignell-usgs for the dc bug report.
> fix readme

- ctd/ctd.py
@rsignell-usgs this is not ready yet and needs some testing, but here is a way to parse the time too.
> parse NMEA time from cnv files

- .stickler.yml
- ctd/utilities.py
- requirements.txt
- tests/test_ctd.py
- tests/test_plotting.py
- tests/test_processing.py
> Convert tests to pytest

- ctd/ctd.py
> Unify bottle and cnv parsers

- ctd/ctd.py
Small fix to set number of stats set dynamically with len(rowtypes) rather that being hardcoded.
> change to len(rowtypes) from hardcoded number of stats in from_btl

- ctd/ctd.py
- tests/test_ctd.py
- tests/test_plotting.py
Hi!
Some suggested changes to fix deprecation warnings and some issues with attribute calls in the tests.  
:-)Bror
> Fix some warnings in from_btl and from_cnv.

- README.md
Some left-overs from ReST to Markdown.
> more docs fixes

- ctd/processing.py
- tests/test_processing.py
- tests/test_processing_real_data.py
Split processing into fake data and real observations tests.
> better testing

- ctd/plotting.py
> improved plotting

- ctd/processing.py
- always return a copy and make all method df and series
> Improve some processing methods

- .travis.yml
Create a dev, versioned, and current doc page.
> versioned docs

- ctd/plotting.py
Implement some recommendations of the upstream  on how to wrap a matplotlib `ax`/
> matplotlib recommended way to wrap ax

- .travis.yml
- requirements-dev.txt
This should make the code base more robust to receive PRs.
> tarball tests and pre-commit

- requirements.txt
Last change before new release.
> update pandas flavor version

- .github/workflows/pypi.yml
> Publish to pypi

- .binder/environment.yml
> Add ctd to environment

- .pre-commit-config.yaml
- tests/test_plotting.py
> Fix pre commits
